trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Testing Mend CLI IN Azure!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  # Install required packages including curl and PHP package manager (composer)
  - script: |
      sudo apt-get update
      sudo apt-get install -y curl php-cli unzip
      curl -sS https://getcomposer.org/installer | php
      sudo mv composer.phar /usr/local/bin/composer
    displayName: 'Install dependencies including PHP package manager'

  # Download Mend CLI with multiple retry logic
  - script: |
      MAX_RETRIES=3
      RETRY_DELAY=10
      for ((i=1; i<=MAX_RETRIES; i++)); do
        echo "Attempt $i to download Mend CLI..."
        curl -L -o mend-cli.zip https://app.whitesourcesoftware.com/resources/cli-agent/download/Mend-cli.zip
        if file mend-cli.zip | grep -q "Zip archive data"; then
          echo "Successfully downloaded Mend CLI."
          break
        elif [ $i -lt $MAX_RETRIES ]; then
          echo "Failed to download Mend CLI. Retrying in $RETRY_DELAY seconds..."
          sleep $RETRY_DELAY
        else
          echo "Failed to download Mend CLI after $MAX_RETRIES attempts. Exiting."
          exit 1
        fi
      done

      unzip mend-cli.zip -d mend-cli || { echo "Failed to unzip Mend CLI."; exit 1; }
      chmod +x mend-cli/mend
    displayName: 'Download and extract Mend CLI'

  # Set environment variables for Mend CLI authentication
  - script: |
      export MEND_SCA_URL=https://app-eu.whitesourcesoftware.com
      export MEND_SCA_EMAIL="$(MEND_SCA_EMAIL)"
      export MEND_SCA_USER_KEY="$(MEND_SCA_USER_KEY)"
      export MEND_SCA_ORG_UUID="$(MEND_SCA_ORG_UUID)"
      export MEND_SCA_API_URL=https://api-app-eu.whitesourcesoftware.com/api/v2.0
      export MEND_LOG_LEVEL=DEBUG
    displayName: 'Set Mend environment variables'

  # Install project dependencies using Composer
  - script: |
      composer install
    displayName: 'Install PHP dependencies'

  # Run Mend SCA CLI to scan the project
  - script: |
      ./mend-cli/mend dep -d . -s "Organization//product//project" -u
    displayName: 'Run Mend SCA CLI scan'
